# syntax=docker/dockerfile:1
# building coar
FROM ocaml/opam:ubuntu-25.10-ocaml-5.4 AS builder
USER opam:opam
RUN sudo apt update && sudo apt install -y \
        libblas-dev \
        libffi-dev \
        libglpk-dev \
        libgmp-dev \
        liblapack-dev \
        libmpfr-dev \
        pkg-config \
        python3 \
 && sudo apt clean \
 && sudo rm -rf /var/lib/apt/lists/*
RUN sudo ln -f /usr/bin/opam-2.3 /usr/bin/opam
# RUN opam repo add alpha git+https://github.com/kit-ty-kate/opam-alpha-repository.git
COPY --chown=opam:opam ./CoAR.opam /home/opam/coar/CoAR.opam
WORKDIR /home/opam/coar
# Limit parallel compilation to avoid Docker OOM
ENV OPAMJOBS=1
ENV DUNEJOBS=1
ENV MAKEFLAGS="-j1"

# build libraries
RUN opam option jobs=1 --global \
 && opam update \
 && opam install -y -j 1 dune \
 && opam install -y -j 1 . --deps-only
# build coar
COPY --chown=opam:opam . /home/opam/coar/
RUN eval $(opam env) && dune build -j 1 main.exe

FROM ubuntu:25.10
RUN apt update \
 && apt install -y \
        libblas-dev \
        libffi-dev \
        libglpk-dev \
        libgmp-dev \
        liblapack-dev \
        libmpfr-dev \
        pkg-config \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*
# Copy the stub library to call libz3 from coar
COPY --from=builder /home/opam/.opam/5.4/lib/stublibs/libz3.so /usr/lib/x86_64-linux-gnu/
COPY --from=builder /home/opam/.opam/5.4/lib/stublibs/libz3.so /usr/lib/aarch64-linux-gnu/
# Copy the stub library to call apron from coar
COPY --from=builder /home/opam/.opam/5.4/share/apron/lib/*.so /usr/lib/x86_64-linux-gnu/
COPY --from=builder /home/opam/.opam/5.4/share/apron/lib/*.so /usr/lib/aarch64-linux-gnu/
# Copy coar
COPY --from=builder /home/opam/coar/_build/default/main.exe /root/coar/
COPY README.md LICENSE CoAR.opam /root/coar/
COPY config /root/coar/config
# Copy ocaml library for ocaml program verification
COPY --from=builder /home/opam/.opam/5.4/lib/ocaml /home/opam/.opam/5.4/lib/ocaml

# Prepare another copies for redistribution with self-contained zip file
COPY --from=builder /home/opam/.opam/5.4/share/apron/lib/*.so /opt/apron/lib/

ENV PATH="${PATH}:/root/coar"
CMD ["/bin/bash"]
